[package]
name = "transfer-sol-example"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.0"
solana-program = "1.18.14"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
solana-logger = "1.18.14"
solana-sdk = "1.18.14"
solana-validator = "1.18.14"
